# -*- coding: utf-8 -*-
"""ARC_RL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y102a5a9RIsKgVEt47Z6ffyN50eJlcYY
"""

# CarRacing-v3 with Synthetic LiDAR + PPO (Stable-Baselines3)
# Goal: Train a policy that transfers to a real vehicle with a 720-beam LiDAR

!pip install stable-baselines3[extra] Box2D gymnasium

import gymnasium as gym
import numpy as np
import math
import torch
import matplotlib.pyplot as plt
from matplotlib import animation
from IPython.display import HTML, display

from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.callbacks import EvalCallback

print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# ============================================================
# LiDAR Constants & Core Raycasting Math
# ============================================================
# Real sensor: 720 beams, 360°. We use front 90° (180 beams) downsampled to 45 rays.
LIDAR_NUM_RAYS = 45
LIDAR_FOV = np.pi / 2        # 90° forward arc
LIDAR_MAX_RANGE = 50.0        # Max range in Box2D world units
TRACK_WIDTH = 40.0 / 6.0      # From CarRacing source: TRACK_WIDTH = 40/SCALE, SCALE=6.0

# Precompute ray angles relative to car heading (centered on 0 = straight ahead)
LIDAR_ANGLES = np.linspace(-LIDAR_FOV / 2, LIDAR_FOV / 2, LIDAR_NUM_RAYS)

# Speed normalization constant (approximate max speed in CarRacing)
MAX_SPEED = 50.0


def compute_track_boundaries(track):
    """Convert track centerline into left/right boundary line segments.

    Args:
        track: list of (alpha, beta, x, y) tuples from env.unwrapped.track

    Returns:
        left_segs:  (N, 2, 2) array — each row is [[x1,y1], [x2,y2]]
        right_segs: (N, 2, 2) array
    """
    n = len(track)
    left_points = np.zeros((n, 2))
    right_points = np.zeros((n, 2))

    for i, (alpha, beta, cx, cy) in enumerate(track):
        # Offset perpendicular to track direction (beta is the heading angle)
        dx = TRACK_WIDTH * math.cos(beta + math.pi / 2)
        dy = TRACK_WIDTH * math.sin(beta + math.pi / 2)
        left_points[i] = [cx + dx, cy + dy]
        right_points[i] = [cx - dx, cy - dy]

    # Build segments: connect consecutive points, wrapping around for closed loop
    left_segs = np.stack([left_points, np.roll(left_points, -1, axis=0)], axis=1)
    right_segs = np.stack([right_points, np.roll(right_points, -1, axis=0)], axis=1)

    return left_segs, right_segs


def cast_lidar_rays(car_pos, car_angle, left_segs, right_segs):
    """Cast LiDAR rays and return distances to nearest track boundary.

    Args:
        car_pos:    (2,) array — car world position
        car_angle:  float — car heading in radians
        left_segs:  (N, 2, 2) — left boundary segments
        right_segs: (N, 2, 2) — right boundary segments

    Returns:
        distances: (LIDAR_NUM_RAYS,) array — distance per ray, capped at LIDAR_MAX_RANGE
    """
    # Combine left and right boundary segments
    all_segs = np.concatenate([left_segs, right_segs], axis=0)  # (2N, 2, 2)

    # Prefilter: only test segments within range of the car
    seg_centers = all_segs.mean(axis=1)  # (2N, 2)
    dists_to_car = np.linalg.norm(seg_centers - car_pos, axis=1)
    mask = dists_to_car < (LIDAR_MAX_RANGE + TRACK_WIDTH * 2)
    nearby_segs = all_segs[mask]  # (M, 2, 2)

    if len(nearby_segs) == 0:
        return np.full(LIDAR_NUM_RAYS, LIDAR_MAX_RANGE)

    # Ray directions in world frame
    world_angles = car_angle + LIDAR_ANGLES  # (R,)
    ray_dirs = np.stack([np.cos(world_angles), np.sin(world_angles)], axis=1)  # (R, 2)

    # Segment vectors
    A = nearby_segs[:, 0]  # (M, 2) — segment start points
    B = nearby_segs[:, 1]  # (M, 2) — segment end points
    AB = B - A              # (M, 2)

    # Vectorized ray-segment intersection
    # For each (ray, segment) pair, compute intersection parameters t and s
    P = car_pos  # (2,)
    AP = A - P   # (M, 2)

    # Cross product helper: 2D cross product = a[0]*b[1] - a[1]*b[0]
    # We need: cross(D, AB) for each ray D and each segment AB
    # ray_dirs: (R, 2), AB: (M, 2)
    # Result shapes: (R, M)
    D_cross_AB = ray_dirs[:, 0, None] * AB[None, :, 1] - ray_dirs[:, 1, None] * AB[None, :, 0]
    AP_cross_AB = AP[:, 0] * AB[:, 1] - AP[:, 1] * AB[:, 0]  # (M,)
    AP_cross_D = AP[None, :, 0] * ray_dirs[:, 1, None] - AP[None, :, 1] * ray_dirs[:, 0, None]  # (R, M)

    # Avoid division by zero for parallel rays
    parallel = np.abs(D_cross_AB) < 1e-10
    D_cross_AB_safe = np.where(parallel, 1.0, D_cross_AB)

    t = AP_cross_AB[None, :] / D_cross_AB_safe   # (R, M) — distance along ray
    s = AP_cross_D / D_cross_AB_safe              # (R, M) — position along segment [0,1]

    # Valid hit: t > 0 (forward along ray) and 0 <= s <= 1 (within segment)
    valid = (~parallel) & (t > 1e-6) & (s >= 0) & (s <= 1) & (t <= LIDAR_MAX_RANGE)

    # For each ray, find the minimum t among valid hits
    t_masked = np.where(valid, t, LIDAR_MAX_RANGE)
    distances = t_masked.min(axis=1)  # (R,)

    return distances


print(f"LiDAR config: {LIDAR_NUM_RAYS} rays, {np.degrees(LIDAR_FOV):.0f}° FOV, max range {LIDAR_MAX_RANGE}")
print(f"Ray angular spacing: {np.degrees(LIDAR_ANGLES[1] - LIDAR_ANGLES[0]):.2f}°")

# ============================================================
# LiDAR Observation Wrapper
# ============================================================
class LiDARWrapper(gym.ObservationWrapper):
    """Replaces image observation with LiDAR rays + car state vector.

    Observation format (48 dims):
        [0:45]  — LiDAR ray distances, normalized to [0, 1] by LIDAR_MAX_RANGE
        [45]    — Forward speed, normalized by MAX_SPEED
        [46]    — Lateral speed, normalized by MAX_SPEED
        [47]    — Angular velocity, normalized (clipped to [-1, 1])
    """

    def __init__(self, env, noise_std=0.0):
        super().__init__(env)
        self.noise_std = noise_std
        self.left_segs = None
        self.right_segs = None

        # New observation space: 45 lidar + 3 car state = 48
        self.observation_space = gym.spaces.Box(
            low=0.0, high=1.0, shape=(LIDAR_NUM_RAYS + 3,), dtype=np.float32
        )

    def reset(self, **kwargs):
        obs, info = self.env.reset(**kwargs)
        # Compute track boundaries for this episode's track
        track = self.unwrapped.track
        self.left_segs, self.right_segs = compute_track_boundaries(track)
        return self.observation(obs), info

    def observation(self, obs):
        car = self.unwrapped.car
        if car is None:
            return np.zeros(LIDAR_NUM_RAYS + 3, dtype=np.float32)

        # Car state
        pos = np.array([car.hull.position[0], car.hull.position[1]])
        angle = car.hull.angle
        vel = car.hull.linearVelocity
        ang_vel = car.hull.angularVelocity

        # Decompose velocity into forward/lateral relative to car heading
        forward_dir = np.array([math.cos(angle), math.sin(angle)])
        lateral_dir = np.array([-math.sin(angle), math.cos(angle)])
        vel_vec = np.array([vel[0], vel[1]])
        forward_speed = np.dot(vel_vec, forward_dir)
        lateral_speed = np.dot(vel_vec, lateral_dir)

        # Cast LiDAR rays
        distances = cast_lidar_rays(pos, angle, self.left_segs, self.right_segs)

        # Add noise for domain randomization (training only)
        if self.noise_std > 0:
            noise = np.random.normal(0, self.noise_std * LIDAR_MAX_RANGE, size=distances.shape)
            distances = np.clip(distances + noise, 0, LIDAR_MAX_RANGE)

        # Normalize everything to [0, 1]
        lidar_norm = distances / LIDAR_MAX_RANGE
        forward_norm = np.clip(forward_speed / MAX_SPEED, -1.0, 1.0) * 0.5 + 0.5
        lateral_norm = np.clip(lateral_speed / MAX_SPEED, -1.0, 1.0) * 0.5 + 0.5
        angvel_norm = np.clip(ang_vel / 5.0, -1.0, 1.0) * 0.5 + 0.5

        observation = np.concatenate([
            lidar_norm,
            [forward_norm, lateral_norm, angvel_norm]
        ]).astype(np.float32)

        return observation


print("LiDARWrapper defined — observation shape:", (LIDAR_NUM_RAYS + 3,))

"""## Environment Setup & Sanity Check"""

# ============================================================
# Environment Factory + Vectorized Envs
# ============================================================
ENV_ID = "CarRacing-v3"

def make_env(noise_std=0.0, render_mode=None):
    def _init():
        env = gym.make(ENV_ID, continuous=True, render_mode=render_mode)
        env = LiDARWrapper(env, noise_std=noise_std)
        return env
    return _init

# 4 parallel training envs with slight LiDAR noise for domain randomization
train_env = DummyVecEnv([make_env(noise_std=0.02) for _ in range(4)])

# Clean eval env (no noise)
eval_env = DummyVecEnv([make_env(noise_std=0.0)])

# Sanity check
obs = train_env.reset()
print(f"Observation shape: {obs.shape}")     # Should be (4, 48)
print(f"Observation range: [{obs.min():.3f}, {obs.max():.3f}]")
print(f"Action space: {train_env.action_space}")
print(f"\nSample observation:\n  LiDAR (first 10 rays): {obs[0, :10]}")
print(f"  Car state [fwd_speed, lat_speed, ang_vel]: {obs[0, -3:]}")

# ============================================================
# PPO Model with MlpPolicy
# ============================================================
model = PPO(
    "MlpPolicy",
    train_env,
    policy_kwargs=dict(net_arch=dict(pi=[256, 256], vf=[256, 256])),
    learning_rate=3e-4,
    n_steps=2048,           # Steps per env before update (2048 * 4 envs = 8192 samples/update)
    batch_size=128,
    n_epochs=10,
    gamma=0.99,
    gae_lambda=0.95,
    clip_range=0.2,
    ent_coef=0.01,          # Entropy bonus for exploration
    vf_coef=0.5,
    max_grad_norm=0.5,
    verbose=1,
    device="cuda",
    tensorboard_log="./ppo_lidar_tb/",
)

print(model.policy)

# ============================================================
# Train PPO with LiDAR (~15-20 min on T4 for 1M steps)
# ============================================================
eval_callback = EvalCallback(
    eval_env,
    best_model_save_path="./ppo_lidar_best/",
    log_path="./ppo_lidar_logs/",
    eval_freq=25_000 // 4,    # Divided by n_envs
    n_eval_episodes=5,
    deterministic=True,
    verbose=1,
)

TOTAL_TIMESTEPS = 1_000_000

model.learn(
    total_timesteps=TOTAL_TIMESTEPS,
    callback=eval_callback,
    progress_bar=True,
)

# Save final model
model.save("ppo_lidar_final")
print("Final model saved!")

# ============================================================
# Evaluate Best Model
# ============================================================
best_model = PPO.load("./ppo_lidar_best/best_model", device="cuda")

mean_reward, std_reward = evaluate_policy(
    best_model, eval_env, n_eval_episodes=10, deterministic=True
)
print(f"Best model — Mean reward: {mean_reward:.1f} +/- {std_reward:.1f}")

# ============================================================
# Plot Training Curves
# ============================================================
results = np.load("./ppo_lidar_logs/evaluations.npz")
timesteps = results["timesteps"]
eval_results = results["results"]

mean_rewards = eval_results.mean(axis=1)
std_rewards = eval_results.std(axis=1)

plt.figure(figsize=(12, 5))
plt.plot(timesteps, mean_rewards, label="Mean eval reward", color="steelblue")
plt.fill_between(timesteps, mean_rewards - std_rewards, mean_rewards + std_rewards, alpha=0.2)
plt.xlabel("Timesteps")
plt.ylabel("Reward")
plt.title("PPO + LiDAR Training Progress — CarRacing-v3")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# ============================================================
# Record Video with LiDAR Visualization Overlay
# ============================================================
import base64
import cv2
import subprocess

def draw_lidar_on_frame(frame, car_pixel_pos, car_angle, distances):
    """Overlay LiDAR rays on an RGB frame.

    Args:
        frame: (H, W, 3) RGB array
        car_pixel_pos: (x, y) pixel position of car in the frame
        car_angle: car heading in radians
        distances: (45,) raw LiDAR distances
    """
    overlay = frame.copy()
    cx, cy = int(car_pixel_pos[0]), int(car_pixel_pos[1])

    for i, (angle_offset, dist) in enumerate(zip(LIDAR_ANGLES, distances)):
        world_angle = car_angle + angle_offset
        # Scale distance to pixels (approximate: ~6.0 pixels per world unit at default zoom)
        pixel_dist = dist * 6.0
        ex = int(cx + pixel_dist * math.cos(world_angle))
        ey = int(cy - pixel_dist * math.sin(world_angle))  # y is flipped in pixel coords

        # Color: red (close) -> yellow -> green (far)
        ratio = min(dist / LIDAR_MAX_RANGE, 1.0)
        r = int(255 * (1 - ratio))
        g = int(255 * ratio)
        color = (r, g, 0)

        cv2.line(overlay, (cx, cy), (ex, ey), color, 1, cv2.LINE_AA)
        cv2.circle(overlay, (ex, ey), 2, color, -1)

    # Blend overlay
    return cv2.addWeighted(overlay, 0.7, frame, 0.3, 0)


def record_video_with_lidar(model, env_id, max_steps=1000):
    """Record frames with LiDAR rays overlaid."""
    render_env = gym.make(env_id, continuous=True, render_mode="rgb_array")
    lidar_env = LiDARWrapper(render_env, noise_std=0.0)

    obs, _ = lidar_env.reset()
    frames = []

    for _ in range(max_steps):
        # Get RGB frame for display
        rgb_frame = render_env.render()
        if rgb_frame is None:
            break

        # Get car state for overlay
        car = render_env.unwrapped.car
        if car is not None:
            pos = np.array([car.hull.position[0], car.hull.position[1]])
            angle = car.hull.angle
            distances = cast_lidar_rays(pos, angle, lidar_env.left_segs, lidar_env.right_segs)

            # Convert car world position to pixel position in the frame
            # CarRacing renders at 96x96 with the car roughly centered
            h, w = rgb_frame.shape[:2]
            car_pixel = (w // 2, int(h * 0.75))  # Car is centered horizontally, ~75% down

            frame_with_lidar = draw_lidar_on_frame(rgb_frame, car_pixel, angle, distances)
            frames.append(frame_with_lidar)
        else:
            frames.append(rgb_frame)

        # Step with the LiDAR observation
        action, _ = model.predict(obs.reshape(1, -1), deterministic=True)
        obs, reward, terminated, truncated, _ = lidar_env.step(action[0])
        if terminated or truncated:
            break

    lidar_env.close()
    return frames


def display_video_mp4(frames, fps=30, filename="car_lidar.mp4"):
    """Save as MP4 and display inline in Colab."""
    h, w = frames[0].shape[:2]
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    out = cv2.VideoWriter(filename, fourcc, fps, (w, h))
    for frame in frames:
        out.write(cv2.cvtColor(frame, cv2.COLOR_RGB2BGR))
    out.release()

    # Re-encode with H.264 for browser playback
    subprocess.run(
        ["ffmpeg", "-y", "-i", filename, "-vcodec", "libx264",
         "-f", "mp4", "_playable.mp4", "-loglevel", "quiet"],
        check=True,
    )

    with open("_playable.mp4", "rb") as f:
        mp4_data = base64.b64encode(f.read()).decode()
    display(HTML(f"""
        <video width="480" controls autoplay loop>
            <source src="data:video/mp4;base64,{mp4_data}" type="video/mp4">
        </video>
    """))


print("Recording simulation with LiDAR overlay...")
video_frames = record_video_with_lidar(best_model, ENV_ID, max_steps=1000)
print(f"Recorded {len(video_frames)} frames")
display_video_mp4(video_frames)

# ============================================================
# Export Policy for Real Vehicle Deployment
# ============================================================
print("=" * 60)
print("OBSERVATION FORMAT CONTRACT FOR REAL VEHICLE")
print("=" * 60)
print(f"""
Input vector: {LIDAR_NUM_RAYS + 3} dimensions (float32, all in [0, 1])

Indices [0:{LIDAR_NUM_RAYS}] — LiDAR ray distances:
  - {LIDAR_NUM_RAYS} rays spanning {np.degrees(LIDAR_FOV):.0f}° forward arc
  - Angular spacing: {np.degrees(LIDAR_ANGLES[1] - LIDAR_ANGLES[0]):.2f}°
  - Ray order: left-to-right (index 0 = {np.degrees(LIDAR_ANGLES[0]):.1f}°, index {LIDAR_NUM_RAYS-1} = {np.degrees(LIDAR_ANGLES[-1]):.1f}°)
  - Normalized: distance / {LIDAR_MAX_RANGE} (clip to [0, 1])
  - Real sensor: use every 4th beam from front 180 beams of 720-beam sensor

Index [{LIDAR_NUM_RAYS}] — Forward speed:
  - speed / {MAX_SPEED} mapped to [0, 1] via: clip(speed/max, -1, 1) * 0.5 + 0.5
  - 0.5 = stationary, >0.5 = forward, <0.5 = reverse

Index [{LIDAR_NUM_RAYS + 1}] — Lateral speed:
  - Same normalization as forward speed

Index [{LIDAR_NUM_RAYS + 2}] — Angular velocity:
  - ang_vel / 5.0 mapped to [0, 1] via: clip(ang_vel/5, -1, 1) * 0.5 + 0.5

Output: 3 continuous actions
  - [0] Steering: [-1, 1] (left to right)
  - [1] Gas:      [0, 1]
  - [2] Brake:    [0, 1]
""")

# Save model in a format easy to load on the vehicle
best_model.save("ppo_lidar_deploy")
print("Model saved to ppo_lidar_deploy.zip")